#!/bin/bash

verbose=0
minutes=5
min_arg=0

args=()
for opt in $@; do
  if [[ "$opt" =~ ^--?vv*$ ]]; then
    verbose=$(grep -o "v" <<<"$opt" | wc -l)
  else
    args=( "${args[@]}" "$opt" )
  fi
done

if [[ -n "$min_arg" && "$min_arg" =~ ^[0-9]+$ ]]; then
  minutes=$min_arg
fi

chance_pic_pct=42
total_pics=400
chance_pics=$((total_pics * chance_pic_pct / 100))
safe_pics=0
edge_pics=$((chance_pics * 60 / 100))
rand_pics=$((chance_pics - (safe_pics + edge_pics)))
porn_pics=$((total_pics - (safe_pics + edge_pics + rand_pics)))

$HOME/toys/sexy-slideshow $safe_pics $edge_pics $rand_pics $porn_pics 3.2 &
sexy_pid=$!

armed=0
# Russian Roulette
if [[ $((RANDOM % 6)) -eq 0 ]]; then
  armed=1
fi

now=$(date +"%s")
program='/tmp/stroke-session'

state_file="$HOME/.config/sessions.state"

cat << EOF > "$$state_file"
start_time          $now
icy_active_count    0
no_icy_until        40
no_lube_until       20
max_time            500
run_time            0
final_pace          0
match_count         0
match_gap           0
icy_countdown       0
checkins            0
pictures_seen       0
icy_break           40
icy_chance          0
icy_armed           $armed
icy_active          0
lube_break          20
EOF

base=20
ready=0
icymaxmax=100
icymax=$icymaxmax
while [[ $ready -ne 1 ]]; do
  icymax=$((icymaxmax - (RANDOM % base)))
  if [[ $((icymax % 5)) -eq 0 ]]; then
    ready=1
  fi
  base=$((base + 5))
done

"$HOME/toys/pacer" -icymax $icymax "${args[@]}"

grep -e '#[^ ]' "$program" | while read message; do
  if ! echo "$message" | grep -q 'icy'; then
    echo "$message" | cut -d' ' -f2-
  fi
done
echo "Tempo Ramps:  $(grep '# start:' "$program" | wc -l)"

do_cleanup() {
  local pid program
  pid=$1
  program=$2
  if ps $pid &>/dev/null; then
    kill $pid
  fi
  rm -f "$program"
  exit
}

trap "do_cleanup "$sexy_pid" "$program"" SIGINT SIGTERM



last_bpm=0
aoss "$HOME/bin/ctronome" -c 1 -w1 "$HOME/toys/tick.wav" \
  -w2 "$HOME/toys/tock.wav" -p "$program" | while read info; do
    if echo "$info" | grep -qe '^#icy'; then
      to_add=$(<"$icy_add_pics")
      icy=$(<"$icy_pics")
      echo $((icy + to_add)) > "$icy_pics"
    fi
    bpm=$(echo "$info" | grep -e '^BPM:' | cut -c6-)
    if [[ -n "$bpm" ]]; then
      if [[ $verbose -eq 2 ]]; then
        $HOME/toys/show-bpm "$bpm"
      elif [[ $verbose -eq 1 ]]; then
        if [[ $bpm -gt $last_bpm ]]; then
          "$HOME/toys/show-bpm" "+"
        elif [[ $bpm -lt $last_bpm ]]; then
          "$HOME/toys/show-bpm" "-"
        else
          "$HOME/toys/show-bpm" "$bpm"
        fi
        last_bpm=$bpm
      fi
    fi
  done

if ps $sexy_pid &>/dev/null; then
  kill $sexy_pid
fi

do_cleanup "$sexy_pid" "$program"
