#!/bin/bash

image=$1
number=$2

user_id=1
prefix=bonus

db="$HOME/.config/edgr.sqlite"

base_image="${image##*/}"
win_prize=0

# Images that I probably shouldn't be using
demerits=0
if [[ "$base_image" =~ ^special ]]; then
  demerits=$((RANDOM%8 + RANDOM%8 + RANDOM%8))
  win_prize=1
fi

# Images that have been added by add-bonus-pics
if [[ "$base_image" =~ ^$prefix ]]; then
  demerits=$(echo "$base_image" | sed -n "s/^$prefix-\([0-9]*\).*/\1/p")
  if [[ -z "$demerits" || "$demerits" =~ [^0-9] ]]; then
    demerits=1
  fi
fi

if [[ "$demerits" -gt 0 ]]; then
  sql="update user_data set val=val+$demerits where user_id=$user_id and key='ante'"
  sqlite3 "$db" "$sql"
  sql="select val from user_data where key='ante' and user_id=$user_id"
  if [[ "$win_prize" -eq 0 ]]; then
    ante=$(sqlite3 "$db" "$sql")
    printf "Ante: %s\n" "$ante"
  fi
fi

if [[ "$win_prize" -gt 0 ]]; then
  sql="select val from user_data where key='ante' and user_id=$user_id"
  ante=$(sqlite3 "$db" "$sql")

  sql="select val from user_data where key='slideshow' and user_id=$user_id"
  possible=$(sqlite3 "$db" "$sql")

  # Increase slideshow
  sql="update user_data set val=val+(select val from user_data where key = 'ante' and user_id=$user_id) where key = 'slideshow' and user_id=$user_id"
  sqlite3 "$db" "$sql"

  # Reset ante
  sql="update user_data set val=0 where key='ante' and user_id=$user_id"
  sqlite3 "$db" "$sql"

  printf "%s + %s = %s\n" "$possible" "$ante" "$((possible+ante))"
fi
