#!/usr/bin/env python3

import time
import random
from playsound import playsound
import os

audio_dir = "%s/lib/audio" % os.environ['HOME']

def main():
  edges = int(input("Number of edges: "))

  warm_ups = [ 5, 5, 10, 10, 10, 15, 15, 15, 20 ]

  time.sleep(random.choice(warm_ups) * 60)

  play_rand_sound(audio_dir + "/get-ready")

  while edges > 0:
    countdowns = [ 30, 30,
                   45, 45, 45, 45,
                   60, 60, 60, 60, 60, 60,
                   90, 90, 90,
                   120, 120,
                   180 ]

    time.sleep(random.choice(countdowns))

    start = time.time()

    play_rand_sound(audio_dir + "/edges")

    input("Press Enter once you get to the edge.")

    elapsed = time.time() - start

    print("Edge took %s seconds" % elapsed)

    if elapsed > 30:
      play_rand_sound(audio_dir + "/too-slow")
    else:
      edges = edges - 1

def play_rand_sound(directory):
  if os.path.isdir(directory):
    filename = ''

    while not os.path.isfile(directory + '/' + filename):
      filename = random.choice(os.listdir(directory))

    playsound(directory + '/' + filename)

  return

if __name__ == '__main__':
  main()
