#!/usr/bin/env python3

import time
import random
from playsound import playsound
import os

from signal import signal, SIGINT
from sys import exit
import threading

home_dir = os.environ['HOME']
audio_dir = f'{home_dir}/lib/audio'

edge_min = 15
edge_max = 90

def main():
  global edge_max, edge_min

  edges = int(input("Number of edges: "))

  print("Stroke yourself!")
  play_rand_sound(f'{audio_dir}/stroke')

  # Sleep for 5-10 minutes.
  time.sleep(random.randint(300,600))

  print("Hands off your cock.")
  play_rand_sound(f'{audio_dir}/hands-off')

  while edges > 0:
    fh = open(f'{home_dir}/.edgr_slaps', 'r')
    count = int(fh.readline())
    fh.close()

    if count > 0:
      if count > 10:
        count = 10

      mp3 = f'{audio_dir}/slaps/slap-balls-indian-{count:02}.mp3'
      sound_thread = threading.Thread(target=playsound, args=(mp3,))
      sound_thread.start()

      fh = open(f'{home_dir}/.edgr_slaps', 'w')
      fh.write('0\n')
      fh.close()

    time.sleep(random.randint(10,20))

    print("Get ready to edge, stroke yourself!")
    play_rand_sound(f'{audio_dir}/stroke')

    time.sleep(int(random.choices(
      population  = [15, 30, 45, 60, 90, 120, 180, 300],
      weights     = [10, 15, 20, 50, 30,  15,   8,   1],
      k           = 1
    )[0]))

    for foo in range(0,5):
      if random.randint(1,20) == 1:
        play_rand_sound(f'{audio_dir}/laughs')
        time.sleep(random.randint(15,60))

    print("Edge for me.")
    play_rand_sound(f'{audio_dir}/edges')

    start = time.time()

    input("Press Enter once you get to the edge.")

    elapsed = time.time() - start

    print("Hands off your cock.")
    play_rand_sound(f'{audio_dir}/hands-off')

    time.sleep(random.randint(10,20))

    if elapsed > edge_max:
      print("Too slow, try again.")
      play_rand_sound(f'{audio_dir}/too-slow')
    else:
      print("Good boy.")
      play_rand_sound(f'{audio_dir}/good-boy')
      if elapsed > edge_max - 1:
        print("That was close!")
      if elapsed > edge_min:
        edge_max = elapsed
      edges = edges - 1

    time.sleep(5)

  # Done!
  print("You may stop stroking your cock.")
  play_rand_sound(f'{audio_dir}/stop')

def play_rand_sound(directory):
  if os.path.isdir(directory):
    filename = ''

    while not os.path.isfile(f'{directory}/{filename}'):
      filename = random.choice(os.listdir(directory))

    mp3 = f'{directory}/{filename}'
    sound_thread = threading.Thread(target=playsound, args=(mp3,))
    sound_thread.start()

  return

def handler(signal_received, frame):
  print()
  exit(0)

if __name__ == '__main__':
  # Run handler() when SIGINT received
  signal(SIGINT, handler)

  main()
