#!/usr/bin/env python3

import time
import random
from playsound import playsound
import os

audio_dir = "%s/lib/audio" % os.environ['HOME']

def main():
  edges = int(input("Number of edges: "))

  warm_ups = [ 6, 6, 6, 6, 6, 9, 9, 9, 9, 12, 12, 15 ]

  time.sleep(random.choice(warm_ups) * 60)

  play_rand_sound(audio_dir + "/get-ready")

  while edges > 0:
    countdowns = [ 30, 30,
                   45, 45, 45, 45,
                   60, 60, 60, 60, 60, 60,
                   90, 90, 90 ]

    if random.randint(1,50) == 1:
      countdowns = [ x + 30 for x in countdowns ]

    if random.randint(1,50) == 1:
      countdowns = [ x + 30 for x in countdowns ]

    if random.randint(1,100) == 1:
      countdowns = [ x + 60 for x in countdowns ]

    time.sleep(random.choice(countdowns))

    start = time.time()

    play_rand_sound(audio_dir + "/edges")

    input("Press Enter once you get to the edge.")

    elapsed = time.time() - start

    print("Edge took %s seconds" % elapsed)

    if elapsed > 15:
      play_rand_sound(audio_dir + "/too-slow")
    else:
      edges = edges - 1

def play_rand_sound(directory):
  if os.path.isdir(directory):
    filename = ''

    while not os.path.isfile(directory + '/' + filename):
      filename = random.choice(os.listdir(directory))

    playsound(directory + '/' + filename)

  return

if __name__ == '__main__':
  main()
