#!/bin/bash

right=5
if [[ -n "$1" && "$1" =~ ^[0-9]*$ ]]; then
  right="$1"
fi

wrong=10
if [[ -n "$2" && "$2" =~ ^[0-9]*$ ]]; then
  wrong="$2"
fi

win_streak=1
if [[ -n "$3" && "$3" =~ ^[0-9]*$ ]]; then
  win_streak="$3"
fi

lose_streak=5
if [[ -n "$4" && "$4" =~ ^[0-9]*$ ]]; then
  lose_streak="$4"
fi

score=60
if [[ -n "$5" && "$5" =~ ^[0-9]*$ ]]; then
  score="$5"
fi

delay=20

for i in $(seq 1 $win_streak); do
  if [[ $((RANDOM%2)) -eq 1 ]]; then
    delay=$((delay + 3))
  fi
done

delay=$(printf "%0.2g" "$(echo "(16 + 2 * $win_streak) / 10" | bc -l)")

img_dst=/tmp/edging

seed=$(((right + wrong) * 5))

safe="$right + ($win_streak * 10)"
safe=$(printf "%.0f" $(echo "$safe" | bc -l))

edge="($lose_streak * $wrong * ((100 - $score) / 100))"
edge="$wrong + ($lose_streak * 15)"
edge=$(printf "%.0f" $(echo "$edge" | bc -l))

$HOME/toys/sexy-slideshow $safe $edge $seed 0 $delay &
pid=$!

seconds=$(printf "%.0f" \
  $(echo "$lose_streak * 30 * ((100 - $score) / 100)" | bc -l))
echo "$seconds"

for i in $(seq 1 $seconds); do
  sleep 1
  if ! ps $pid &>/dev/null; then
    break
  fi
done

if ps $pid &>/dev/null; then
  kill $pid
fi
