#!/bin/bash

right=5
if [[ -n "$1" ]]; then
  if [[ "$1" =~ ^[0-9]*$ ]]; then
    right="$1"
  fi
fi


wrong=10
if [[ -n "$2" ]]; then
  if [[ "$2" =~ ^[0-9]*$ ]]; then
    wrong="$2"
  fi
fi

win_streak=1
if [[ -n "$3" ]]; then
  if [[ "$3" =~ ^[0-9]*$ ]]; then
    win_streak="$3"
  fi
fi

lose_streak=5
if [[ -n "$4" ]]; then
  if [[ "$4" =~ ^[0-9]*$ ]]; then
    lose_streak="$4"
  fi
fi

score=60
if [[ -n "$5" ]]; then
  if [[ "$5" =~ ^[0-9]*$ ]]; then
    score="$5"
  fi
fi

delay=20

for i in $(seq 1 $win_streak); do
  if [[ $((RANDOM%2)) -eq 1 ]]; then
    delay=$((delay + 3))
  fi
done

delay=$(printf "%0.2g" "$(echo "$delay / 10" | bc)")

config="$HOME/.config/geeqie/geeqierc.xml"
sed -rie "s/(slideshow.delay\s*=).*$/\1 \"$delay\"/" "$config"
sed -rie "s/(slideshow.repeat\s*=).*/\1 \"true\"/" "$config"

#config="$HOME/.config/mirage/miragerc"
#sed -rie "s/^(slideshow_delay =).*$/\1 $delay/" "$config"

img_dst=/tmp/edging
mkdir -p "$img_dst"

seed=$((right * (right - (right * score / 100))))
image_src=$HOME/files/images/sexy/

while read file; do
  base_filename=${file##*/}
  link_name=$(printf "%s-%s" "seed" "$base_filename")
  ln -s "$file" "$img_dst/$link_name"
done < <(find "$img_src" -regextype posix-egrep -iregex '.*\.(jpe?g|nef)' \
  | shuf \
  | head -n ${seed})

echo "$seed sexy + possible edging photos"

safe=$((right * win_streak))
image_src=$HOME/files/images/sexy/

while read file; do
  base_filename=${file##*/}
  link_name=$(printf "%s-%s" "safe" "$base_filename")
  ln -s "$file" "$img_dst/$link_name"
done < <(find "$img_src" -maxdepth 1 -regextype posix-egrep \
  -iregex '.*\.(jpe?g|nef)' \
  | shuf \
  | head -n ${safe})

echo "$safe safe photos"

edge=$((lose_streak + wrong))
image_src=$HOME/files/images/sexy/edges/

while read file; do
  base_filename=${file##*/}
  link_name=$(printf "%s-%s" "edge" "$base_filename")
  ln -s "$file" "$img_dst/$link_name"
done < <(find "$img_src" -regextype posix-egrep -iregex '.*\.(jpe?g|nef)' \
  | shuf \
  | head -n ${edge})

echo "$edge edging photos"

#/usr/bin/mirage -f -s -o "$HOME/toys/track-edges /tmp/$$.edges %F" "$img_dst" &
/usr/bin/geeqie -f -s "$img_dst" &>/dev/null &
pid=$!

seconds=$(((wrong * 20) - ((right * 10 * score) / 100)))
echo "$seconds"
for i in $(seq 1 $seconds); do
  sleep 1
  if ! ps $pid &>/dev/null; then
    break
  fi
done

if ps $pid &>/dev/null; then
  kill $pid
fi

# clean up
sed -rie "s/(slideshow.repeat\s*=).*/\1 \"false\"/" "$config"
rm -rf "$img_dst"
