#!/usr/bin/env python3

import os
import time
import random
import re
import sqlite3
import argparse
import subprocess

home_dir = os.environ['HOME']

def main():
  user_id = 1

  dbh = sqlite3.connect(f'{home_dir}/.config/edgr.sqlite')
  sth = dbh.cursor()
  args = do_cli_args()

  count = 0
  slap  = 0
  risk  = 0

  image = str(args.file[0])

  if image.find('porn_pics') > 0:
    query = 'select count from seen_images where user_id=? and filename=?'
    sth.execute(query,(user_id, image))
    dbh.commit()
    count = sth.fetchone()
    if count != None:
      count = count[0] + 1
      query = 'update seen_images set count=? where user_id=? and filename=?'
      sth.execute(query,(count, user_id, image))
      dbh.commit()
      print(f'Seen {count}x')
    else:
      query = """insert into seen_images ('user_id', 'filename', 'count')
                  values (?,?,?)"""
      sth.execute(query, (user_id, image, 1))
      dbh.commit()
      count = 1

    if count > 1:
      high_die = int(4 + int(args.right))
      for i in range(2, int(args.wrong) + count):
        if random.randint(1, high_die) == 1:
          slap = slap + 1

  if (image.find('risky')) > 0:
    query = """ update settings set value = value + ? where name = ? """
    sth.execute(query,(1,'risk'))
    dbh.commit()

    query = """ select value from settings where name = ? """
    sth.execute(query, ('slaps',))
    current = int(sth.fetchone()[0])

    if current > 0:
      query = """ update settings set value = value + ? where name = ? """
      sth.execute(query, (random.randint(0, 2), 'slaps',))
      dbh.commit()

    query = """ select value from settings where name = ? """
    sth.execute(query, ('risk',))
    risk = sth.fetchone()[0]

    for i in range(1, 3):
      if risk > random.randint(0, 100):
        slap = slap + 1

  if slap > 0:
    slaps = random.randint(1, slap)
    query = """ update settings set value = value + ? where name = ? """
    sth.execute(query,(slaps,'slaps'))
    dbh.commit()

  query = """ select value from settings where name = ? """
  sth.execute(query,('save_pics',))
  saves = int(sth.fetchone()[0])

  if saves > 1:
    print(f'Saves: {saves}x')
  elif saves == 1:
    print(f'Save: {saves}x')

  dbh.close()

def do_cli_args():
  parser = argparse.ArgumentParser()

  parser.add_argument(
    '-r', '--right',
    default=2,
    type=int,
    help='Number pictures in a row right from Thong Game',
  )

  parser.add_argument(
    '-w', '--wrong',
    default=4,
    type=int,
    help='Number pictures in a row wrong from Thong Game',
  )

  parser.add_argument(
    '-f', '--file',
    nargs='+',
    help='Full path of file',
  )

  return parser.parse_args()

if __name__ == '__main__':
  main()
