#!/bin/bash

prior_days=10
new_pic_start=1644782400
old_pic_start=$((new_pic_start - (prior_days * 24 * 60 * 60)))

old_pic_mins=5
new_pic_mins=20

db="$HOME/.config/edgr.sqlite"

directories=( "$HOME/files/images/porn_pics" "$HOME/files/images/captions" )

all_pic_count=$(for dir in ${directories[@]}; do
  find "$dir" -type f -newermt "@${old_pic_start}"
done | wc -l)

new_pic_count=$(for dir in ${directories[@]}; do
  find "$dir" -type f -newermt "@${new_pic_start}"
done | wc -l)

init_time=$(((all_pic_count - new_pic_count) * old_pic_mins))
more_time=$((new_pic_count * new_pic_mins))

owed_sex=$(((init_time + more_time) * 60))

stroked=$(sqlite3 "$db" "select sum(duration) from session_time where time > $new_pic_start")

if [[ "$stroked" -gt 0 ]]; then
  echo "$($HOME/tools/human-sex "$stroked") stroked so far"
fi

echo "$($HOME/tools/human-sex "$((owed_sex - stroked))") left to stroke"

if [[ "$stroked" -gt "$owed_sex"  ]]; then
  printf "green light\n"
else
  printf "red light\n"
fi
