#!/usr/bin/perl

# todo:
# finish algorithm to calculate goal
# use more functions
# test goals
# add considerations for distance from mean / std dev
# add considerations for coin flips
# determine how failure and success should affect things

use strict;
use warnings;

use Edgr;
use Getopt::Long;

my $conf_file   = "$ENV{HOME}/.config/edgr";

main();
exit;

sub main {
  my $conf = read_config($conf_file);
  my $session = init_session($conf);

  GetOptions(
    "random"    => \$$session{random},
  );

  my $dbh = db_connect($$session{database});
  # Add "next_session_in" check; restrict sessions, and consequecences for
  # trying again too soon. Have a chance of allowing it, and adding punishment
  # to next session for not passing
  while ($$session{time_max} > $$session{duration}) {
    make_beats($session);
    #print "$$session{time_max} > $$session{duration}\n";
  }
  # Reset for interleaving commands in script
  $$session{duration} = 0;
  write_script($session);
  play_script($session);
  save_session($session);

  my $sql = "select count(*) from sessions where user = ?";
  my $sth = $dbh->prepare($sql);
  $sth->execute($$session{user});
  my ($session_count) = $sth->fetchrow_array;

  my $message = `/usr/games/fortune -n80 -a zippy`;
  if ($$session{endured} >= $$session{goal} - $$session{goal_under} and
      $$session{endured} <= $$session{goal} + $$session{goal_over}) {
    printf "\n\nPass - Draw a bead\n\n";
    #twitters($session,"$message: Session passed! :D");
  } else {
    my $missed_by = $$session{goal} - $$session{goal_under}
                      - $$session{endured};
    if ($$session{endured} > $$session{goal} + $$session{goal_over}) {
      $missed_by = $$session{endured} - $$session{goal} + $$session{goal_over};
    }
    my $beads = 1;
    if ($missed_by > 45) {
      $beads += 1;
    } elsif ($missed_by > 90) {
      $beads += 1;
    }
    my $string = 'bead';
    if ($beads > 1) {
      $string = 'beads';
    }
    printf "\n\n Fail - Add %i %s\n\n", $beads, $string;
    #twitters($session,"$message: Session failed. :(");
  }
}
