#!/bin/bash

file="$1"
trash="${2:-0}"

db="$HOME/.config/edgr.sqlite"
bad_porn_dir="$HOME/files/images/bad_porn"
bad_caps_dir="$HOME/files/images/bad_caps"
good_porn_dir="$HOME/files/images/good_porn"
good_caps_dir="$HOME/files/images/good_caps"

if [[ -z "$file" ]]; then
  echo "Please pass path of image to move to $good_porn_dir"
  exit 1
fi

if [[ ! -f "$file" ]]; then
  echo "File does not exist or is not a file; $file"
  exit 2
fi

if [[ "$file" =~ risky ]]; then
  echo "Not touching risky file; $file"
  exit 3
fi

if [[ "$file" =~ captions ]]; then
  if [[ "$trash" -eq 0 ]]; then
    mv "$file" "$good_caps_dir"
  else
    mv "$file" "$bad_caps_dir"
  fi
else
  query="select count from seen_images where filename == '$file'"
  seen=$(/usr/bin/sqlite3 "$db" "$query")

  query="select value from settings where name == 'save_pics'"
  saves=$(/usr/bin/sqlite3 "$db" "$query")

  if [[ "$trash" -eq 0 ]]; then
    if [[ "$saves" -ge 0 ]]; then
      # Decrement number of saves.
      query="update settings set value = value - 1 where name == 'save_pics'"
      /usr/bin/sqlite3 "$db" "$query"
    else
      $HOME/projects/edgr/edgr-add-slaps --min 1 --max $((seen + 1))
    fi

    mv "$file" "$good_porn_dir"
  else
    mv "$file" "$bad_porn_dir"
  fi
fi
