#!/usr/bin/env python3

import os
import time
import random
import re
import sqlite3
import argparse
import subprocess

home_dir = os.environ['HOME']

def main():
  dbh = sqlite3.connect(f'{home_dir}/.config/edgr.sqlite')
  sth = dbh.cursor()
  args = do_cli_args()

  slaps = random.randint(int(args.min), int(args.max))

  query = """ update settings set value = value + ? where name = ? """
  sth.execute(query,(slaps,'slaps'))
  dbh.commit()

  dbh.close()

def do_cli_args():
  parser = argparse.ArgumentParser()

  parser.add_argument(
    '--min',
    default=1,
    type=int,
    help='Minimum slaps to add',
  )

  parser.add_argument(
    '--max',
    default=3,
    type=int,
    help='Maximum slaps to add',
  )

  return parser.parse_args()

if __name__ == '__main__':
  main()
