#!/bin/bash

file="$1"

db="$HOME/.config/edgr.sqlite"
bad_porn_dir="$HOME/files/images/bad_porn"
bad_caps_dir="$HOME/files/images/captions/wordy"

if [[ -z "$file" ]]; then
  echo "Please pass path of image to move to $good_porn_dir"
  exit 1
fi

if [[ ! -f "$file" ]]; then
  echo "File does not exist or is not a file; $file"
  exit 2
fi

if [[ "$file" =~ risky ]]; then
  echo "Not touching risky file; $file"
  exit 3
fi

query="select count from seen_images where filename == '$file'"
seen=$(/usr/bin/sqlite3 "$db" "$query")

query="select value from settings where name == 'to_purge'"
to_purge=$(/usr/bin/sqlite3 "$db" "$query")

if [[ "$seen" -gt 4 ]]; then
  $HOME/projects/edgr/edgr-add-slaps --min 1 --max $((seen + 1))
fi

if [[ "$to_purge" -gt 0 ]]; then
  if [[ "$file" =~ captions ]]; then
    mv "$file" "$bad_caps_dir"
  else
    mv "$file" "$bad_porn_dir"
    # Decrement number of saves.
    query="update settings set value = value - 1 where name == 'to_purge'"
    /usr/bin/sqlite3 "$db" "$query"
  fi
fi
