#!/bin/bash

source $HOME/lib/edgr_funcs.sh

streak_right="${1:-4}"
streak_wrong="${2:-0}"
wrong_answers="${3:-40}"

edge_limit=$((wrong_answers + 15))

edge_limit=1024

# string accepted by date '-d' option
pic_window='12 hours ago'

wrong_answers=$((find $HOME/files/images/porn_pics -type f -newermt "$pic_window"; \
                 find $HOME/files/images/captions  -type f -newermt "$pic_window") | wc -l)

script="$HOME/projects/edgr/edgr-check-image"
images="$HOME/files/images/porn_pics/pool"
slideshow="$HOME/.edgr_slideshow"

/usr/bin/sqlite3 "$HOME/.config/edgr.sqlite" \
          "update settings set value = 0 where name = 'risk'"
/usr/bin/sqlite3 "$HOME/.config/edgr.sqlite" \
          "update settings set value = 0 where name = 'slaps'"
#/usr/bin/sqlite3 "$HOME/.config/edgr.sqlite" \
#          "update settings set value = 1 where name = 'edges'"
/usr/bin/sqlite3 "$HOME/.config/edgr.sqlite" \
          "update settings set value = 0 where name = 'stage'"
/usr/bin/sqlite3 "$HOME/.config/edgr.sqlite" \
          "update settings set value = 0 where name = 'red_light'"
/usr/bin/sqlite3 "$HOME/.config/edgr.sqlite" \
          "update settings set value = $wrong_answers where name = 'to_purge'"

now=$(date "+%s")

porn_pics=500

caption_pct=$((40 - (streak_right * 5)))
caption_pics=$((porn_pics * caption_pct / 100))

risky_pct=$((5 + (streak_wrong * 5)))
risky_pics=$(((porn_pics + caption_pics) * risky_pct / 100))

random_pic_playlist "$HOME/files/images/porn_pics/pool" $porn_pics > "$slideshow"
random_pic_playlist "$HOME/files/images/captions" $caption_pics >> "$slideshow"
random_pic_playlist "$HOME/files/images/risky" "$risky_pics" >> "$slideshow"

red_light=$(random_pic_playlist "$HOME/files/images/risky" 1)

#$HOME/projects/edgr/edgr-slappr &
$HOME/projects/edgr/edgr-beater &

$HOME/bin/feh -f "$slideshow" \
  --info "$script --file %f --right $streak_right --wrong $streak_wrong --red $red_light --edgelimit $edge_limit" \
  --auto-zoom \
  --hide-pointer \
  --borderless \
  --no-jump-on-resort \
  --randomize \
  --scale-down \
  --image-bg black \
  --geometry 1500x1050+15+15 \
  --slideshow-delay 7 \
  --slideshow-delay-min 7 \
  --slideshow-delay-max 7 \
  --action "$HOME/projects/edgr/edgr-sortedge %F" \
  --action1 ";$HOME/projects/edgr/edgr-edge %F" \
  --fontpath "$HOME/.local/share/fonts/Lexend_Giga/" \
  --font "LexendGiga-Regular/22"

end_time=$(date +"%s")

stroke_time=$((end_time - now))

printf "\nStroked for %s\n" "$(sec_to_human $stroke_time)"

pkill -f edgr-slappr
pkill -f edgr-beater
