#!/bin/bash

source $HOME/lib/edgr_funcs.sh

right="$1" || 0
wrong="$2" || 10

script="$HOME/projects/edgr/edgr-check-image"
pics_count="$HOME/.edge_pics"
images="$HOME/files/images/porn_pics"
slideshow="$HOME/.slideshow"

rm -f "$HOME/.edgr_psych"
rm -f "$HOME/.edgr_since_points"
echo "$wrong" > "$HOME/.edgr_slaps"
echo 25 > "$HOME/.edgr_slapchance"

now=$(date "+%s")

pics=2

start_pics=0
start_pics_min=50

while [[ "$start_pics" -lt "$start_pics_min" ]]; do
  start_pics=$((RANDOM % 50 + start_pics_min))

  for i in $(seq 1 $right); do
    if [[ "$((RANDOM % 3))" -eq 0 ]]; then
      start_pics=$((start_pics - RANDOM % 5))
    fi
  done

  for i in $(seq 1 $((wrong * 2))); do
    if [[ "$((RANDOM % 3))" -eq 0 ]]; then
      start_pics=$((start_pics + RANDOM % 5))
    fi
  done
done

dupes=0
dupes_min=140

while [[ "$dupes" -lt "$dupes_min" ]]; do
  dupes=$((RANDOM % 40 + dupes_min))

  for i in $(seq 1 $right); do
    if [[ "$((RANDOM % 3))" -eq 0 ]]; then
      dupes=$((dupes - RANDOM % 10))
    fi
  done

  for i in $(seq 1 $((wrong * 2))); do
    if [[ "$((RANDOM % 3))" -eq 0 ]]; then
      dupes=$((dupes + RANDOM % 10))
    fi
  done
done

countdown=0
countdown_min=5
countdown_max=7

while [[ "$countdown" -lt "$countdown_min" ]] || \
      [[ "$countdown" -gt "$countdown_max" ]]; do
  countdown=$((RANDOM % 3 + countdown_min))

  for i in $(seq 1 $right); do
    if [[ "$((RANDOM % 3))" -eq 0 ]]; then
      countdown=$((countdown - 1))
    fi
  done

  for i in $(seq 1 $((wrong * 2))); do
    if [[ "$((RANDOM % 3))" -eq 0 ]]; then
      countdown=$((countdown + 1))
    fi
  done
done

echo 0 > "$HOME/.edge_remains"
echo "$start_pics" > "$pics_count"

safe_pics=3400
porn_pics=$((RANDOM % safe_pics))
caption_pics=$((safe_pics - porn_pics))

random_pic_playlist "$HOME/files/images/porn_pics/stash $HOME/files/images/porn_pics" $porn_pics > "$slideshow"
random_pic_playlist "$HOME/files/images/captions" $caption_pics >> "$slideshow"
random_pic_playlist "$HOME/files/images/risky" "$dupes" >> "$slideshow"

# Shuffle the slideshow list
shuf "$slideshow" -o "$slideshow"

$HOME/bin/feh -f "$slideshow" \
  --info "$script %f $pics_count $pics $start_pics $countdown $right $wrong" \
  --auto-zoom \
  --hide-pointer \
  --borderless \
  --no-jump-on-resort \
  --randomize \
  --scale-down \
  --image-bg black \
  --geometry 1500x1080+0+0 \
  --slideshow-delay 4 \
  --slideshow-delay-min 2 \
  --slideshow-delay-max 6 \
  --action1 "mv %F ~/files/images/rejects/%N" \
  --fontpath /usr/share/fonts/truetype/dejavu/ \
  --font DejaVuSans/18

end_time=$(date +"%s")

stroke_time=$((end_time - now))

printf "\nStroked for %s\n" "$(sec_to_human $stroke_time)"
printf "dupes: %s\nstart pics: %s\ncountdown: %s\n" $dupes $start_pics $countdown
printf "slaps: %s\n" $(< "$HOME/.edgr_slaps")
