#!/bin/bash

file="$1"

db="$HOME/.config/edgr.sqlite"
good_porn_dir="$HOME/files/images/good_porn"
good_caps_dir="$HOME/files/images/good_caps"

if [[ -z "$file" ]]; then
  echo "Please pass path of image to move to $good_porn_dir"
  exit 1;
fi

query="select value from settings where name == 'save_pics'"
saves=$(/usr/bin/sqlite3 "$db" "$query")

# Add a punishment for required saves
if [[ "$saves" -ge 0 ]]; then
  $HOME/projects/edgr/edgr-add-slaps --min 0 --max 3
fi

# Decrement number of saves.
query="update settings set value = value - 1 where name == 'save_pics'"
/usr/bin/sqlite3 "$db" "$query"

if [[ -e "$file" ]]; then
  if [[ "$file" =~ captions ]]; then
    mv "$file" "$good_caps_dir"
  else
    mv "$file" "$good_porn_dir"
  fi

  query="select count from seen_images where filename == '$file'"
  seen=$(sqlite3 "$db" "$query")
  if [[ "$seen" -eq 1 ]]; then
    $HOME/projects/edgr/edgr-add-slaps --min 2 --max 3
  else
    $HOME/projects/edgr/edgr-add-slaps --min 0 --max $((seen + 2))
  fi
fi
