#!/usr/bin/perl

# todo:
# finish algorithm to calculate goal
# use more functions
# test goals
# add considerations for distance from mean / std dev
# add considerations for coin flips
# determine how failure and success should affect things

use strict;
use warnings;

use Edgr;
use Getopt::Long;

my $conf_file   = "$ENV{HOME}/.config/edgr";

main();
exit;

sub main {
  my $conf = read_config($conf_file);
  my $session = init_session($conf);

  GetOptions(
    "random"    => \$$session{random},
  );

  my $dbh = db_connect($$session{database});
  # Add "next_session_in" check; restrict sessions, and consequecences for
  # trying again too soon. Have a chance of allowing it, and adding punishment
  # to next session for not passing
  while ($$session{time_max} > $$session{duration}) {
    make_beats($session);
  }
  # Reset for interleaving commands in script
  $$session{duration} = 0;
  write_script($session);
  play_script($session);
  save_session($session);

  my $extra_beads = 0;

  my $sql = qq{ select * from sessions where user = ?
              and date >= datetime('now',?) order by date };
  my $sth = $dbh->prepare($sql);
  $sth->execute($$session{user},$$session{past_hours});

  while (my $sesh = $sth->fetchrow_hashref) {
    $extra_beads++;
    if ($$sesh{length} > $$sesh{goal} + $$session{goal_over}) {
      $extra_beads = 0;
    }
    if ($$sesh{length} < $$sesh{goal} - $$session{goal_under}) {
      $extra_beads = 0;
    }
  }

  if ($$session{endured} >= $$session{goal} - $$session{goal_under} and
      $$session{endured} <= $$session{goal} + $$session{goal_over}) {
    printf "\n\nPass - Draw a bead\n\n";
  } else {
    printf "\n\n Fail - Add %s\n\n",
                ($extra_beads + 1> 1)?"$beads beads":"a bead";
  }
}
