#!/bin/bash
num=50
if [[ -n "$1" && "$1" =~ ^[0-9]*$ ]]; then
  num=$1
fi

time=300
if [[ -n "$2" ]]; then
  if [[ "$2" =~ ^[0-9]*$ ]]; then
    time="$(($2 * 60))"
  elif [[ "$2" =~ ^[0-9]*s$ ]]; then
    time="${2%%s*}"
  fi
fi

delay=20
delay=$((delay + $((RANDOM%20))))
delay=$((delay + $((RANDOM%20))))
delay=$((delay - $((RANDOM%10))))
delay=$((delay - $((RANDOM%10))))
if [[ $delay -lt 8 ]]; then
  delay=8
fi
delay=$(echo "$delay / 10" | bc -l)

config="$HOME/.config/geeqie/geeqierc.xml"
sed -rie "s/(slideshow.delay\s*=).*$/\1 \"$delay\"/" "$config"
sed -rie "s/(slideshow.repeat\s*=).*/\1 \"true\"/" "$config"

image_dst=/tmp/stroking
mkdir -p "$image_dst"

(
  find $HOME/files/images/sexy -regextype posix-egrep \
    -iregex '.*\.(jpe?g|nef)';
  find $HOME/files/images -regextype posix-egrep \
    -iregex '.*\.(jpe?g|nef)';
  find $HOME/files/downloads/images -regextype posix-egrep \
    -iregex '.*\.(jpe?g|nef)';
) | shuf \
  | head -n${num} \
  | while read file; do
    cp "$file" "$image_dst"
  done

find $HOME/files/images/sexy -regextype posix-egrep \
  -iregex '.*\.(jpe?g|nef)' | shuf \
  | head -n${num} \
  | while read file; do
    cp "$file" "$image_dst"
  done

/usr/bin/geeqie -f -s "$image_dst" &>/dev/null &
pid=$!

for i in $(seq 1 $time); do
  sleep 1
  if ! ps $pid &>/dev/null; then
    printf "%g seconds remaining\n" $((time - i))
    break
  fi
done

if ps $pid &>/dev/null; then
  kill $pid
fi

# clean up
sed -rie "s/(slideshow.repeat\s*=).*/\1 \"false\"/" "$config"
rm -rf "$image_dst"
