#!/bin/bash
time=300
if [[ -n "$1" ]]; then
  if [[ "$1" =~ ^[0-9]*$ ]]; then
    time="$(($1 * 60))"
  elif [[ "$1" =~ ^[0-9]*s$ ]]; then
    time="${1%%s*}"
  fi
fi

config="$HOME/.config/geeqie/geeqierc.xml"
sed -rie "s/(slideshow.delay\s*=).*$/\1 \"5\"/" "$config"
sed -rie "s/(slideshow.repeat\s*=).*/\1 \"true\"/" "$config"

$HOME/toys/sexy-slideshow 50 50 100 150 &
pid=$!

for i in $(seq 1 $time); do
  sleep 1
  if ! ps $pid &>/dev/null; then
    printf "%g seconds remaining\n" $((time - i))
    break
  fi
done

if ps $pid &>/dev/null; then
  kill $pid
fi

# clean up
sed -rie "s/(slideshow.repeat\s*=).*/\1 \"false\"/" "$config"
rm -rf "$image_dst"
