#!/bin/bash

verbose=0
minutes=5
min_arg=0

while getopts "m:v" OPTION; do
  case "$OPTION" in
    m) min_arg="$OPTARG" ;;
    v) verbose=$((verbose + 1)) ;;
    *) ;;
  esac
done

if [[ -n "$min_arg" && "$min_arg" =~ ^[0-9]+$ ]]; then
  minutes=$min_arg
fi

$HOME/toys/sexy-slideshow 20 50 100 250 4 &
sexy_pid=$!

program="/tmp/stroke-program.$$"
"$HOME/toys/pacer" -m $minutes > "$program"
echo "Tempo Ramps:  $(grep '# start:' "$program" | wc -l)"

last_bpm=0
aoss "$HOME/bin/ctronome" -c 1 -w1 "$HOME/toys/tick.wav" \
  -w2 "$HOME/toys/tock.wav" -p "$program" | while read info; do
    bpm=$(echo "$info" | grep -e '^BPM:' | cut -c6-)
    if [[ -n "$bpm" ]]; then
      if [[ $verbose -eq 2 ]]; then
        $HOME/toys/show-bpm "$bpm"
      elif [[ $verbose -eq 1 ]]; then
        if [[ $bpm -gt $last_bpm ]]; then
          "$HOME/toys/show-bpm" "+"
        elif [[ $bpm -lt $last_bpm ]]; then
          "$HOME/toys/show-bpm" "-"
        else
          "$HOME/toys/show-bpm" "$bpm"
        fi
        last_bpm=$bpm
      fi
    fi
  done

if ps $sexy_pid &>/dev/null; then
  kill $sexy_pid
fi
