#!/bin/bash

source $HOME/lib/edgr_funcs.sh

script="$HOME/projects/edgr/add_time"
pics_count="$HOME/.edge_pics"
images="$HOME/files/images/porn_pics"
slideshow="$HOME/.slideshow"

now=$(date "+%s")

dupes=120
start_pics=20
pics=2

for i in {1..6}; do
  roll=$((RANDOM%6))
  case $roll in
    0)
      for i in {1..10}; do
        dupes=$((dupes + (RANDOM % 10)))
      done
      ;;
    1)
      start_pics=$((start_pics + (RANDOM % 10)))
      start_pics=$((start_pics + (RANDOM % 10)))
      start_pics=$((start_pics + (RANDOM % 10)))
      ;;
    2|3)
      dupes=$((dupes + (RANDOM % 10)))
      dupes=$((dupes + (RANDOM % 10)))
      dupes=$((dupes + (RANDOM % 10)))
      start_pics=$((start_pics + (RANDOM % 10)))
      start_pics=$((start_pics + (RANDOM % 10)))
      ;;
  esac
done

echo 0 > "$HOME/.edge_remains"
echo "$start_pics" > "$pics_count"

random_pic_playlist "$HOME/files/images/porn_pics" 2200 > "$slideshow"
random_pic_playlist "$HOME/files/images/captions" 1200 >> "$slideshow"
random_pic_playlist "$HOME/files/images/risky" "$dupes" >> "$slideshow"

# Shuffle the slideshow list
shuf "$slideshow" -o "$slideshow"

printf "dupes: %s\npics per point: %s\n" $dupes $pics

$HOME/bin/feh -f "$slideshow" \
  --info "$script %f $pics_count $pics $start_pics" \
  --auto-zoom \
  --hide-pointer \
  --borderless \
  --no-jump-on-resort \
  --randomize \
  --scale-down \
  --image-bg black \
  --geometry 1500x1080+0+0 \
  --slideshow-delay 4 \
  --slideshow-delay-min 2 \
  --slideshow-delay-max 6 \
  --fontpath /usr/share/fonts/truetype/dejavu/ \
  --font DejaVuSans/18

end_time=$(date +"%s")

stroke_time=$((end_time - now))

printf "\nStroked for %s\n" "$(sec_to_human $stroke_time)"
