#!/bin/bash

source $HOME/lib/edgr_funcs.sh

script="$HOME/projects/edgr/add_time"
pics_count="$HOME/.edge_pics"
images="$HOME/files/images/porn_pics"
slideshow="$HOME/.slideshow"

now=$(date "+%s")

dupes=140
start_pics=30
countdown=5
pics=2

for i in {0..15}; do
  roll=$((RANDOM%8))
  case $roll in
    0)
      dupes=$((dupes + 10))
      ;;
    1)
      start_pics=$((start_pics + 5))
      ;;
    2|3)
      dupes=$((dupes + 10))
      start_pics=$((start_pics + 5))
      countdown=$((countdown + 1))
      ;;
    4)
      countdown=$((countdown + 1))
      ;;
  esac
done

echo 0 > "$HOME/.edge_remains"
echo "$start_pics" > "$pics_count"

safe_pics=3400
porn_pics=$((RANDOM % safe_pics))
caption_pics=$((safe_pics - porn_pics))


random_pic_playlist "$HOME/files/images/porn_pics" $porn_pics > "$slideshow"
random_pic_playlist "$HOME/files/images/captions" $caption_pics >> "$slideshow"
random_pic_playlist "$HOME/files/images/risky" "$dupes" >> "$slideshow"

# Shuffle the slideshow list
shuf "$slideshow" -o "$slideshow"

printf "dupes: %s\nstart pics: %s\n" $dupes $start_pics

$HOME/bin/feh -f "$slideshow" \
  --info "$script %f $pics_count $pics $start_pics $countdown" \
  --auto-zoom \
  --hide-pointer \
  --borderless \
  --no-jump-on-resort \
  --randomize \
  --scale-down \
  --image-bg black \
  --geometry 1500x1080+0+0 \
  --slideshow-delay 4 \
  --slideshow-delay-min 2 \
  --slideshow-delay-max 6 \
  --fontpath /usr/share/fonts/truetype/dejavu/ \
  --font DejaVuSans/18

end_time=$(date +"%s")

stroke_time=$((end_time - now))

printf "\nStroked for %s\n" "$(sec_to_human $stroke_time)"
