#!/bin/bash

source $HOME/lib/edgr_funcs.sh

script="$HOME/projects/edgr/add_time"
time_file="$HOME/.edge_after"
images="$HOME/files/images/porn_pics"
slideshow="$HOME/.slideshow"

now=$(date "+%s")

dupes=120
start_time=90
secs=$((RANDOM % 3 + 3))

for i in {1..6}; do
  roll=$((RANDOM%8))
  case $roll in
    0)
      for i in {1..10}; do
        dupes=$((dupes + (RANDOM % 10)))
      done
      ;;
    1)
      start_time=$((start_time + (RANDOM % 45)))
      start_time=$((start_time + (RANDOM % 45)))
      start_time=$((start_time + (RANDOM % 45)))
      ;;
    2)
      secs=$((RANDOM % 2 + $secs))
      secs=$((RANDOM % 2 + $secs))
      ;;
    3|4|5)
      dupes=$((dupes + (RANDOM % 10)))
      dupes=$((dupes + (RANDOM % 10)))
      dupes=$((dupes + (RANDOM % 10)))
      start_time=$((start_time + (RANDOM % 45)))
      secs=$((RANDOM % 2 + $secs))
      ;;
  esac
done

echo $((start_time + now)) > "$time_file"

random_pic_playlist "$HOME/files/images/porn_pics" 2200 > "$slideshow"
random_pic_playlist "$HOME/files/images/captions" 1200 >> "$slideshow"
random_pic_playlist "$HOME/files/images/risky" "$dupes" >> "$slideshow"

# Shuffle the slideshow list
shuf "$slideshow" -o "$slideshow"

printf "time: %s\ndupes: %s\nsecs: %s\n" $start_time $dupes $secs

$HOME/bin/feh -f "$slideshow" \
  --info "$script %f $time_file $secs $start_time" \
  --auto-zoom \
  --hide-pointer \
  --borderless \
  --no-jump-on-resort \
  --randomize \
  --scale-down \
  --image-bg black \
  --geometry 1500x1080+0+0 \
  --slideshow-delay 4 \
  --slideshow-delay-min 2 \
  --slideshow-delay-max 6 \
  --fontpath /usr/share/fonts/truetype/dejavu/ \
  --font DejaVuSans/18

end_time=$(date +"%s")

stroke_time=$((end_time - now))

printf "\nStroked for %s\n" "$(sec_to_human $stroke_time)"
