#!/usr/bin/perl

use strict;
use warnings;

use Sessions;

use Getopt::Long;

my $conf_file = "$ENV{HOME}/.config/sessions";
my $green     = 0;  # Provide 'Green Light!' prompts
my $prompts   = 0;  # Prompt for values for pace, length, etc
my $safe_mode = 0;  # Eliminate chance for Icy Hot lube
my $tg_mode   = 0;  # Thong Game mode; prompt for scores from Thong Game

GetOptions(
  "green"     => \$green,
  "prompt"    => \$prompts,
  "safe"      => \$safe_mode,
  "tg"        => \$tg_mode,
) or die("Error in args");

print "green: $green\n";

# Read in configuration
my $config  = read_config($conf_file);

# Initialize session state
my $state   = init_session_state($config);

# Prompts
if ($tg_mode > 0) {
  $$state{wrong}    = prompt("Answered wrong");
  $$state{win}      = prompt("Win streak");
  $$state{lose}     = prompt("Lose streak");
  $$state{score}    = prompt("Score");
}

if ($prompts > 0) {
  $$state{time_min} = prompt("Min length",$$state{time_min});
  $$state{time_max} = prompt("Max length",$$state{time_max});

  $$state{pace_min} = prompt("Min BPM",$$state{pace_min});
  $$state{pace_max} = prompt("Max BPM",$$state{pace_max});
}

if ($green > 0) {
  $$state{greens}     = prompt("Green Lights",$$state{greens});
  $$state{countdown}  = prompt("Countdwon",$$state{countdown});
}

main($state);

sub main {
  my $playable = 0;

  my $wrong = 0;
  my $win   = 0;
  my $lose  = 0;
  my $score = 0;

  while ($playable == 0) {
    $playable = 1;

    if (10 > $wrong and !int(rand($wrong))) {
      $playable = 0;
    }

    if ($wrong > 20 and int(rand($wrong))) {
      $playable = 0;
    }

    if (5 > $wrong) {
      $playable = 0;
    }

    if ($playable == 0) {
      printf "\nPlay again.\n\n";
    }
  }

  my $args = sprintf('-win %i -lose %i -score %i -wrong %i',
                      $win, $lose, $score, $wrong);


  #$args .= ' -green 2 -greens 2 -yellow 3';

  exec "$ENV{HOME}/toys/master-beater $args";
}
