#!/bin/bash

img_dst=/tmp/sexy_slideshow

safe_pics="$HOME/files/images/sexy/safe/"
edge_pics="$HOME/files/images/sexy/edges/"
seed_pics="$HOME/files/images/sexy/"
rand_pics="$HOME/files/images/ $HOME/files/downloads/images/"

source "$HOME/.config/sexy-slideshow"

safe=$1
edge=$2
seed=$3
rand=$4

rm -rf "$img_dst"
mkdir -p "$img_dst"

link_files() {
  count=$1
  src=$2
  name=$3

  while read file; do
    base=${file##*/}
    link=$(printf "%s-%s" "$name" "$base")
    ln -s "$file" "$img_dst/$link"
  done < <(find $src -regextype posix-egrep -iregex '.*\.(jpe?g|nef)' \
    | shuf \
    | head -n $count)

  echo "$count $name photos"
}

link_files "$safe" "$safe_pics" "safe"
link_files "$edge" "$edge_pics" "edge"
link_files "$seed" "$seed_pics" "seed"
link_files "$rand" "$rand_pics" "rand"

/usr/bin/geeqie -f -s "$img_dst" &>/dev/null &
viewer_pid=$!
trap "kill $viewer_pid; exit" SIGINT SIGTERM
while ps $viewer_pid &>/dev/null; do
  sleep 1
done
