#!/bin/bash

bpm=$1

osd_font='-*-terminus-medium-r-*-*-64-*-*-*-*-*-*-*'
osd_delay=10
osd_options="-p top -A right -o 5 -i 5 -c white -u black -O 4 -l 1"
osd_options="$osd_options -f $osd_font -d $osd_delay"

pkill osd_cat &>/dev/null
echo "$bpm" | osd_cat $osd_options &
